export const SET_LOADING = "SET_LOADING";
export const GET_USERS_REQUESTED = "GET_USERS_REQUESTED";
export const GET_USERS = "GET_USERS";
export const CREATE_USER_REQUESTED = "CREATE_USER_REQUESTED";
export const CREATE_USER = "CREATE_USER";
